# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: web
    main: ./cmd/web
    binary: chronokeyaccess_web
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: cli
    main: ./cmd/cli
    binary: chronokeyaccess_cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: wgreader
    main: ./cmd/wgreader
    binary: chronokeyaccess_wgreader
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    mod_timestamp: "{{ .CommitTimestamp }}"
  - id: dooropener
    main: ./cmd/dooropener
    binary: chronokeyaccess_dooropener
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 6
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: web_archive
    builds: [web]
    name_template: "chronokeyaccess_web_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: cli_archive
    builds: [cli]
    name_template: "chronokeyaccess_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: wgreader_archive
    builds: [wgreader]
    name_template: "chronokeyaccess_wgreader_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: dooropener_archive
    builds: [dooropener]
    name_template: "chronokeyaccess_dooropener_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: web_pkg
    package_name: chronokeyaccess_web
    builds: [web]
    vendor: TheMulle
    homepage: https://github.com/themulle
    maintainer: Manuel M端ller <themulle@gmail.com>
    description: ChronoKeyAccess Web App
    license: Apache 2.0
    formats:
      - deb
    contents:
      - src: ./scripts/web.service
        dst: /etc/systemd/system/chronokeyaccess_web.service
        type: file
    scripts:
      preinstall: ./scripts/web_preinstall.sh
      postinstall: ./scripts/web_postinstall.sh
      postremove: ./scripts/web_postuninstall.sh
  - id: cli_pkg
    package_name: chronokeyaccess_cli
    builds: [cli]
    vendor: TheMulle
    homepage: https://github.com/themulle
    maintainer: Manuel M端ller <themulle@gmail.com>
    description: ChronoKeyAccess Cli App
    license: Apache 2.0
    formats:
      - deb
    provides:
      - chronokeyaccess_cli
    bindir: /usr/bin
  - id: wgreader_pkg
    package_name: chronokeyaccess_wgreader
    builds: [wgreader]
    vendor: TheMulle
    homepage: https://github.com/themulle
    maintainer: Manuel M端ller <themulle@gmail.com>
    description: ChronoKeyAccess Wiegand Reader App
    license: Apache 2.0
    formats:
      - deb
    provides:
      - chronokeyaccess_wgreader
    bindir: /usr/bin
    contents:
      - src: ./scripts/checkandopen.sh
        dst: /etc/chronokeyaccess/checkandopen.sh
        type: file
        file_info:
          mode: 0700
  - id: dooropener_pkg
    package_name: chronokeyaccess_dooropener
    builds: [dooropener]
    vendor: TheMulle
    homepage: https://github.com/themulle
    maintainer: Manuel M端ller <themulle@gmail.com>
    description: ChronoKeyAccess Door Opener App
    license: Apache 2.0
    formats:
      - deb
    provides:
      - chronokeyaccess_dooropener
    bindir: /usr/bin
    

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
